name: MovieFlix
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  #  splashscreen: ^1.3.5
  http: ^0.13.4
  get: ^4.6.1
  get_storage:
  google_fonts:
  splashscreen:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
#  fonts:
#    - family: OpenSans
#      fonts:
#        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
#        - asset: assets/fonts/OpenSans/OpenSans-Light.ttf
#        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf